In [173]:
import pandas as pd
ind49=pd.read_csv("Data/ind49_m_vw_rets.csv", parse_dates=True , index_col=0)

In [52]:
ind49.head()

,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,Clths,...,Boxes,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other
192607,2.37,0.12,-99.99,-5.19,1.29,8.65,2.50,50.21,-0.48,8.08,...,7.70,1.94,-23.79,0.07,1.87,4.61,-0.54,2.89,-4.85,5.20
192608,2.23,2.68,-99.99,27.03,6.50,16.81,-0.76,42.98,-3.58,-2.51,...,-2.38,4.88,5.39,-0.75,-0.13,11.83,2.57,5.30,-0.57,6.76
192609,-0.57,1.58,-99.99,4.02,1.26,8.33,6.42,-4.91,0.73,-0.51,...,-5.54,0.06,-7.87,0.25,-0.56,-1.75,0.72,-3.06,-3.14,-3.86
192610,-0.46,-3.68,-99.99,-3.31,1.06,-1.40,-5.09,5.37,-4.68,0.12,...,-5.08,-2.64,-15.38,-2.20,-4.11,-11.82,-4.28,-5.74,2.07,-8.49
192611,6.75,6.26,-99.99,7.29,4.55,0.00,1.82,-6.40,-0.54,1.87,...,3.84,1.60,4.67,6.52,4.33,-2.97,3.58,2.21,4.92,4.00

In [82]:
type(ind49)

pandas.core.frame.DataFrame

In [89]:
ind49.columns

Index(['Agric', 'Food ', 'Soda ', 'Beer ', 'Smoke', 'Toys ', 'Fun  ', 'Books',
       'Hshld', 'Clths', 'Hlth ', 'MedEq', 'Drugs', 'Chems', 'Rubbr', 'Txtls',
       'BldMt', 'Cnstr', 'Steel', 'FabPr', 'Mach ', 'ElcEq', 'Autos', 'Aero ',
       'Ships', 'Guns ', 'Gold ', 'Mines', 'Coal ', 'Oil  ', 'Util ', 'Telcm',
       'PerSv', 'BusSv', 'Hardw', 'Softw', 'Chips', 'LabEq', 'Paper', 'Boxes',
       'Trans', 'Whlsl', 'Rtail', 'Meals', 'Banks', 'Insur', 'RlEst', 'Fin  ',
       'Other'],
      dtype='object')

In [86]:
beer=ind49.loc['199101':'201812',['Beer ']]
beer

        Beer
199101   4.65
199102  10.84
199103   5.67
199104  -4.01
199105   3.86
199106  -5.74
199107   9.10
199108   5.96
199109  -4.61
199110   2.09
199111   3.03
199112  15.41
199201  -3.06
199202   1.50
199203   1.35
199204   1.90
199205   3.62
199206  -5.49
199207   4.55
199208   1.28
199209  -2.11
199210   2.04
199211   0.70
199212   2.90
199301   0.86
199302  -2.35
199303   2.46
199304  -9.18
199305   3.18
199306   2.01
...       ...
201607   1.84
201608  -0.88
201609   1.65
201610  -1.63
201611  -5.75
201612   3.03
201701  -0.98
201702   6.17
201703   0.92
201704   1.94
201705   4.34
201706  -1.14
201707   1.25
201708   1.03
201709  -2.91
201710   1.33
201711   4.41
201712   4.40
201801  -0.11
201802  -6.76
201803   1.27
201804  -4.29
201805  -1.19
201806   4.42
201807   3.50
201808  -1.86
201809   0.19
201810  -1.57
201811   5.79
201812  -9.69

[336 rows x 1 columns]

In [101]:
beer.iloc[0:10]

        Beer
199101   4.65
199102  10.84
199103   5.67
199104  -4.01
199105   3.86
199106  -5.74
199107   9.10
199108   5.96
199109  -4.61
199110   2.09

In [27]:
import edhec_risk_kit_201 as erk

%load_ext autoreload
%autoreload 2

In [96]:
fff = erk.get_fff_returns()
fff.head()

         Mkt-RF     SMB     HML      RF
1926-07  0.0296 -0.0230 -0.0287  0.0022
1926-08  0.0264 -0.0140  0.0419  0.0025
1926-09  0.0036 -0.0132  0.0001  0.0023
1926-10 -0.0324  0.0004  0.0051  0.0032
1926-11  0.0253 -0.0020 -0.0035  0.0031

In [134]:
fff.loc["1991"]

Mkt-RF    0.0469
SMB       0.0379
HML      -0.0184
RF        0.0052
Name: 1991-01, dtype: float64

In [169]:
fam.head()

        Mkt-RF   SMB   HML    RF
192607    2.96 -2.30 -2.87  0.22
192608    2.64 -1.40  4.19  0.25
192609    0.36 -1.32  0.01  0.23
192610   -3.24  0.04  0.51  0.32
192611    2.53 -0.20 -0.35  0.31

In [177]:
import statsmodels.api as sm
import numpy as np
beer_excess = beer.values - fam.loc[199101:201812, ['RF']].values
mkt_excess = fam.loc[1991:2018-12,['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var["Constant"] = 1
lm = sm.OLS(beer_excess, exp_var).fit()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [100]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.225
Model:                            OLS   Adj. R-squared:                  0.223
Method:                 Least Squares   F-statistic:                     96.99
Date:                Tue, 09 Jun 2020   Prob (F-statistic):           2.94e-20
Time:                        14:22:47   Log-Likelihood:                -950.99
No. Observations:                 336   AIC:                             1906.
Df Residuals:                     334   BIC:                             1914.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Mkt-RF        52.8966      5.371      9.848      0.000      42.331      63.462
Constant       0.6385      0.227      2.808      0.005       0.191       1.086
==============================================================================
Omnibus:                       17.874   Durbin-Watson:                   2.069
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.200
Skew:                          -0.242   Prob(JB):                     5.07e-09
Kurtosis:                       4.579   Cond. No.                         23.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [105]:
steel_excess = ind49.loc['199101':'201812',['Steel']].values - fff.loc["1991":"2018-12", ['RF']].values
mkt_excess = fff.loc["1991":"2018-12",['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var["Constant"] = 1
lm1 = sm.OLS(steel_excess, exp_var).fit()

In [106]:
lm1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.630
Model:                            OLS   Adj. R-squared:                  0.629
Method:                 Least Squares   F-statistic:                     569.9
Date:                Tue, 09 Jun 2020   Prob (F-statistic):           3.43e-74
Time:                        17:01:48   Log-Likelihood:                -1015.6
No. Observations:                 336   AIC:                             2035.
Df Residuals:                     334   BIC:                             2043.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Mkt-RF       155.4034      6.510     23.872      0.000     142.598     168.209
Constant      -0.3450      0.276     -1.252      0.211      -0.887       0.197
==============================================================================
Omnibus:                       24.651   Durbin-Watson:                   2.009
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               42.902
Skew:                           0.453   Prob(JB):                     4.83e-10
Kurtosis:                       4.497   Cond. No.                         23.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [108]:
beer_excess2 = ind49.loc['201301':'201812',['Beer ']].values - fff.loc["201301":"2018-12", ['RF']].values
mkt_excess = fff.loc["2013":"2018-12",['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var["Constant"] = 1
lm2 = sm.OLS(beer_excess2, exp_var).fit()

In [109]:
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.311
Model:                            OLS   Adj. R-squared:                  0.302
Method:                 Least Squares   F-statistic:                     31.66
Date:                Tue, 09 Jun 2020   Prob (F-statistic):           3.53e-07
Time:                        17:05:37   Log-Likelihood:                -175.71
No. Observations:                  72   AIC:                             355.4
Df Residuals:                      70   BIC:                             360.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Mkt-RF        58.2397     10.351      5.626      0.000      37.595      78.885
Constant       0.4905      0.347      1.414      0.162      -0.201       1.182
==============================================================================
Omnibus:                        4.902   Durbin-Watson:                   2.208
Prob(Omnibus):                  0.086   Jarque-Bera (JB):                4.350
Skew:                          -0.597   Prob(JB):                        0.114
Kurtosis:                       3.159   Cond. No.                         31.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [111]:
steel_excess2 = ind49.loc['201301':'201812',['Steel']].values - fff.loc["2013":"2018-12", ['RF']].values
mkt_excess = fff.loc["2013":"2018-12",['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var["Constant"] = 1
lm3 = sm.OLS(steel_excess2, exp_var).fit()

In [112]:
lm3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.469
Model:                            OLS   Adj. R-squared:                  0.462
Method:                 Least Squares   F-statistic:                     61.89
Date:                Tue, 09 Jun 2020   Prob (F-statistic):           3.21e-11
Time:                        17:30:10   Log-Likelihood:                -215.41
No. Observations:                  72   AIC:                             434.8
Df Residuals:                      70   BIC:                             439.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Mkt-RF       141.3381     17.965      7.867      0.000     105.508     177.169
Constant      -0.9377      0.602     -1.557      0.124      -2.139       0.263
==============================================================================
Omnibus:                        7.128   Durbin-Watson:                   2.188
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                6.423
Skew:                           0.634   Prob(JB):                       0.0403
Kurtosis:                       3.732   Cond. No.                         31.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [115]:
lm3.params

Mkt-RF      141.338090
Constant     -0.937746
dtype: float64

In [116]:
ind49.columns

Index(['Agric', 'Food ', 'Soda ', 'Beer ', 'Smoke', 'Toys ', 'Fun  ', 'Books',
       'Hshld', 'Clths', 'Hlth ', 'MedEq', 'Drugs', 'Chems', 'Rubbr', 'Txtls',
       'BldMt', 'Cnstr', 'Steel', 'FabPr', 'Mach ', 'ElcEq', 'Autos', 'Aero ',
       'Ships', 'Guns ', 'Gold ', 'Mines', 'Coal ', 'Oil  ', 'Util ', 'Telcm',
       'PerSv', 'BusSv', 'Hardw', 'Softw', 'Chips', 'LabEq', 'Paper', 'Boxes',
       'Trans', 'Whlsl', 'Rtail', 'Meals', 'Banks', 'Insur', 'RlEst', 'Fin  ',
       'Other'],
      dtype='object')

In [133]:
mkt_excess = fff.loc["1991":"1993-12",['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var["Constant"] = 1
d={}
for columns in ind49.columns:
    col = ind49.loc['199101':'199312',[columns]].values - fff.loc["1991":"1993-12", ['RF']].values
    lmcol = sm.OLS(col, exp_var).fit()
    d[columns]=[]
    d[columns].append(lmcol.params)
    print(columns , lmcol.params)

Agric Mkt-RF      103.454096
Constant      0.032595
dtype: float64
Food  Mkt-RF      126.876856
Constant     -0.570748
dtype: float64
Soda  Mkt-RF      132.519496
Constant     -0.362486
dtype: float64
Beer  Mkt-RF      120.423733
Constant      0.300532
dtype: float64
Smoke Mkt-RF      132.993561
Constant     -1.577742
dtype: float64
Toys  Mkt-RF      106.375538
Constant      1.802700
dtype: float64
Fun   Mkt-RF      103.483369
Constant      1.068104
dtype: float64
Books Mkt-RF      99.298839
Constant     0.459228
dtype: float64
Hshld Mkt-RF      102.033765
Constant      0.399178
dtype: float64
Clths Mkt-RF      152.308676
Constant     -0.127759
dtype: float64
Hlth  Mkt-RF      162.135496
Constant     -0.227839
dtype: float64
MedEq Mkt-RF      148.008482
Constant     -0.764797
dtype: float64
Drugs Mkt-RF      125.489111
Constant     -0.639526
dtype: float64
Chems Mkt-RF      89.459359
Constant     0.378337
dtype: float64
Rubbr Mkt-RF      117.560997
Constant      0.800054
dtype: float64
Txtls Mkt-RF      113.682779
Constant      1.400559
dtype: float64
BldMt Mkt-RF      117.793345
Constant      0.708033
dtype: float64
Cnstr Mkt-RF      152.704176
Constant     -0.862978
dtype: float64
Steel Mkt-RF      95.236460
Constant     0.309831
dtype: float64
FabPr Mkt-RF      125.140782
Constant      0.189892
dtype: float64
Mach  Mkt-RF      109.622749
Constant      0.090858
dtype: float64
ElcEq Mkt-RF      122.395364
Constant      0.648113
dtype: float64
Autos Mkt-RF      75.388058
Constant     1.839094
dtype: float64
Aero  Mkt-RF      79.965133
Constant     0.721673
dtype: float64
Ships Mkt-RF      121.586211
Constant     -0.624303
dtype: float64
Guns  Mkt-RF      56.785881
Constant     1.083983
dtype: float64
Gold  Mkt-RF     -54.712925
Constant     1.401769
dtype: float64
Mines Mkt-RF      28.092103
Constant     1.744387
dtype: float64
Coal  Mkt-RF      53.611702
Constant    -0.599430
dtype: float64
Oil   Mkt-RF      55.676328
Constant     0.124620
dtype: float64
Util  Mkt-RF      38.568688
Constant     0.772380
dtype: float64
Telcm Mkt-RF      72.202671
Constant     0.633028
dtype: float64
PerSv Mkt-RF      97.818380
Constant     0.757867
dtype: float64
BusSv Mkt-RF      103.466435
Constant      0.518847
dtype: float64
Hardw Mkt-RF      102.822905
Constant     -0.669295
dtype: float64
Softw Mkt-RF      161.449949
Constant      0.870319
dtype: float64
Chips Mkt-RF      127.902236
Constant      1.379548
dtype: float64
LabEq Mkt-RF      125.918110
Constant      0.502383
dtype: float64
Paper Mkt-RF      72.336177
Constant     0.215158
dtype: float64
Boxes Mkt-RF      63.997636
Constant     0.638735
dtype: float64
Trans Mkt-RF      117.453470
Constant      0.843469
dtype: float64
Whlsl Mkt-RF      103.827496
Constant      0.551510
dtype: float64
Rtail Mkt-RF      123.355718
Constant      0.464130
dtype: float64
Meals Mkt-RF      115.150235
Constant      0.951787
dtype: float64
Banks Mkt-RF      136.539270
Constant      1.060717
dtype: float64
Insur Mkt-RF      94.225301
Constant     0.785766
dtype: float64
RlEst Mkt-RF      60.540752
Constant     0.937345
dtype: float64
Fin   Mkt-RF      109.770029
Constant      1.623670
dtype: float64
Other Mkt-RF      146.098548
Constant     -1.528618
dtype: float64

In [129]:
d

{'Agric': [Mkt-RF      103.454096
  Constant      0.032595
  dtype: float64], 'Food ': [Mkt-RF      126.876856
  Constant     -0.570748
  dtype: float64], 'Soda ': [Mkt-RF      132.519496
  Constant     -0.362486
  dtype: float64], 'Beer ': [Mkt-RF      120.423733
  Constant      0.300532
  dtype: float64], 'Smoke': [Mkt-RF      132.993561
  Constant     -1.577742
  dtype: float64], 'Toys ': [Mkt-RF      106.375538
  Constant      1.802700
  dtype: float64], 'Fun  ': [Mkt-RF      103.483369
  Constant      1.068104
  dtype: float64], 'Books': [Mkt-RF      99.298839
  Constant     0.459228
  dtype: float64], 'Hshld': [Mkt-RF      102.033765
  Constant      0.399178
  dtype: float64], 'Clths': [Mkt-RF      152.308676
  Constant     -0.127759
  dtype: float64], 'Hlth ': [Mkt-RF      162.135496
  Constant     -0.227839
  dtype: float64], 'MedEq': [Mkt-RF      148.008482
  Constant     -0.764797
  dtype: float64], 'Drugs': [Mkt-RF      125.489111
  Constant     -0.639526
  dtype: float64], 'Chems': [Mkt-RF      89.459359
  Constant     0.378337
  dtype: float64], 'Rubbr': [Mkt-RF      117.560997
  Constant      0.800054
  dtype: float64], 'Txtls': [Mkt-RF      113.682779
  Constant      1.400559
  dtype: float64], 'BldMt': [Mkt-RF      117.793345
  Constant      0.708033
  dtype: float64], 'Cnstr': [Mkt-RF      152.704176
  Constant     -0.862978
  dtype: float64], 'Steel': [Mkt-RF      95.236460
  Constant     0.309831
  dtype: float64], 'FabPr': [Mkt-RF      125.140782
  Constant      0.189892
  dtype: float64], 'Mach ': [Mkt-RF      109.622749
  Constant      0.090858
  dtype: float64], 'ElcEq': [Mkt-RF      122.395364
  Constant      0.648113
  dtype: float64], 'Autos': [Mkt-RF      75.388058
  Constant     1.839094
  dtype: float64], 'Aero ': [Mkt-RF      79.965133
  Constant     0.721673
  dtype: float64], 'Ships': [Mkt-RF      121.586211
  Constant     -0.624303
  dtype: float64], 'Guns ': [Mkt-RF      56.785881
  Constant     1.083983
  dtype: float64], 'Gold ': [Mkt-RF     -54.712925
  Constant     1.401769
  dtype: float64], 'Mines': [Mkt-RF      28.092103
  Constant     1.744387
  dtype: float64], 'Coal ': [Mkt-RF      53.611702
  Constant    -0.599430
  dtype: float64], 'Oil  ': [Mkt-RF      55.676328
  Constant     0.124620
  dtype: float64], 'Util ': [Mkt-RF      38.568688
  Constant     0.772380
  dtype: float64], 'Telcm': [Mkt-RF      72.202671
  Constant     0.633028
  dtype: float64], 'PerSv': [Mkt-RF      97.818380
  Constant     0.757867
  dtype: float64], 'BusSv': [Mkt-RF      103.466435
  Constant      0.518847
  dtype: float64], 'Hardw': [Mkt-RF      102.822905
  Constant     -0.669295
  dtype: float64], 'Softw': [Mkt-RF      161.449949
  Constant      0.870319
  dtype: float64], 'Chips': [Mkt-RF      127.902236
  Constant      1.379548
  dtype: float64], 'LabEq': [Mkt-RF      125.918110
  Constant      0.502383
  dtype: float64], 'Paper': [Mkt-RF      72.336177
  Constant     0.215158
  dtype: float64], 'Boxes': [Mkt-RF      63.997636
  Constant     0.638735
  dtype: float64], 'Trans': [Mkt-RF      117.453470
  Constant      0.843469
  dtype: float64], 'Whlsl': [Mkt-RF      103.827496
  Constant      0.551510
  dtype: float64], 'Rtail': [Mkt-RF      123.355718
  Constant      0.464130
  dtype: float64], 'Meals': [Mkt-RF      115.150235
  Constant      0.951787
  dtype: float64], 'Banks': [Mkt-RF      136.539270
  Constant      1.060717
  dtype: float64], 'Insur': [Mkt-RF      94.225301
  Constant     0.785766
  dtype: float64], 'RlEst': [Mkt-RF      60.540752
  Constant     0.937345
  dtype: float64], 'Fin  ': [Mkt-RF      109.770029
  Constant      1.623670
  dtype: float64], 'Other': [Mkt-RF      146.098548
  Constant     -1.528618
  dtype: float64]}

In [168]:
fam=pd.read_csv("Data/F-F_Research_Data_Factors_m.csv", parse_dates=True ,index_col=0)

In [159]:
fam.head()

   Unnamed: 0  Mkt-RF   SMB   HML    RF
0      192607    2.96 -2.30 -2.87  0.22
1      192608    2.64 -1.40  4.19  0.25
2      192609    0.36 -1.32  0.01  0.23
3      192610   -3.24  0.04  0.51  0.32
4      192611    2.53 -0.20 -0.35  0.31

In [164]:
#fam.loc["1991-01",['HML']]

In [161]:
exp_var["Value"] = fam.loc["1991":"2018-12",['HML']]
exp_var["Size"] = fam.loc["1991":"2018-12",['SMB']]
exp_var.head()

         Mkt-RF  Constant  Value  Size
1991-01  0.0469         1    NaN   NaN
1991-02  0.0719         1    NaN   NaN
1991-03  0.0265         1    NaN   NaN
1991-04 -0.0028         1    NaN   NaN
1991-05  0.0365         1    NaN   NaN

In [178]:
fff.head()

         Mkt-RF     SMB     HML      RF
1926-07  0.0296 -0.0230 -0.0287  0.0022
1926-08  0.0264 -0.0140  0.0419  0.0025
1926-09  0.0036 -0.0132  0.0001  0.0023
1926-10 -0.0324  0.0004  0.0051  0.0032
1926-11  0.0253 -0.0020 -0.0035  0.0031

In [179]:
fff.tail()

         Mkt-RF     SMB     HML      RF
2018-08  0.0344  0.0123 -0.0412  0.0016
2018-09  0.0006 -0.0237 -0.0134  0.0015
2018-10 -0.0768 -0.0468  0.0341  0.0019
2018-11  0.0169 -0.0074  0.0020  0.0018
2018-12 -0.0955 -0.0261 -0.0151  0.0019